# Generated by Django 4.1.3 on 2023-04-27 13:51

from django.db import migrations, models


def create_enterprise_type(apps, schema_editor):
    EnterpriseType = apps.get_model('app', 'EnterpriseType')
    list_enterprise_type = [
        'Завод',
        'Дистрибьютор',
        'Дилерский центр',
        'Крупная розничная сеть',
        'Индивидуальный предприниматель',
    ]
    list_query = []
    for enterprise_type in list_enterprise_type:
        list_query.append(EnterpriseType(type=enterprise_type))
    EnterpriseType.objects.bulk_create(list_query)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnterpriseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RunPython(create_enterprise_type),
    ]

