# Generated by Django 4.1.3 on 2023-04-27 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=32)),
                ("country", models.CharField(max_length=32)),
                ("city", models.CharField(max_length=32)),
                ("the_outside", models.CharField(max_length=32)),
                ("house_number", models.CharField(max_length=32)),
                ("level", models.IntegerField()),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.enterprisetype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnterpriseProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, unique=True)),
                ("model", models.CharField(max_length=64)),
                ("market_launch_date", models.DateField()),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.enterprise"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnterpriseEmployees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.enterprise"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplyChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(blank=True, null=True)),
                ("move_date", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider",
                        to="app.enterprise",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipient",
                        to="app.enterprise",
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "recipient")},
            },
        ),
    ]
