# Generated by Django 4.1.3 on 2023-04-27 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_enterprise_enterpriseproducts_enterpriseemployees_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterpriseemployees",
            name="enterprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="app.enterprise",
            ),
        ),
        migrations.AlterField(
            model_name="enterpriseproducts",
            name="enterprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="app.enterprise",
            ),
        ),
        migrations.AlterField(
            model_name="enterpriseproducts",
            name="name",
            field=models.CharField(max_length=25),
        ),
    ]
