# Generated by Django 4.1.3 on 2023-04-27 13:51
import datetime

from django.conf import settings
from django.db import migrations, models


def create(apps, schema_editor):
    Products = apps.get_model('app', 'Products')

    list_products = [
        ['Asus', '01', f"{datetime.date.today()}"],
        ['Aser', '02', f"{datetime.date.today()}"],
        ['Lenovo', '03', f"{datetime.date.today()}"],
        ['Huawei', '04', f"{datetime.date.today()}"],
        ['Samsung', '05', f"{datetime.date.today()}"],
    ]
    list_query = []
    for value in list_products:
        list_query.append(
            Products(
                name=value[0],
                model=value[1],
                market_launch_date=value[2],
            )
        )
    Products.objects.bulk_create(list_query)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0005_create_entries"),
    ]

    operations = [
        migrations.RunPython(create),
    ]
