# Generated by Django 4.1.3 on 2023-04-27 13:51
import datetime

from django.conf import settings
from django.db import migrations, models


def create(apps, schema_editor):
    Products = apps.get_model('app', 'Products')
    Enterprise = apps.get_model('app', 'Enterprise')
    EnterpriseProducts = apps.get_model('app', 'EnterpriseProducts')
    SupplyChain = apps.get_model('app', 'SupplyChain')

    enterprise_products = {
        1: [1, 2, 3],
        2: [4, 5],
    }
    list_query = []
    for enterprise, list_value in enterprise_products.items():
        enterprise = Enterprise.objects.get(pk=enterprise)
        for product_id in list_value:
            product = Products.objects.get(pk=product_id)
            list_query.append(
                EnterpriseProducts(
                    enterprise=enterprise,
                    products=product,
                )
            )
    EnterpriseProducts.objects.bulk_create(list_query)

    list_supply_chain = [
        [1, 2, 1.2, datetime.datetime.now()],
        [2, 3, 1.2, datetime.datetime.now()],
    ]
    list_query = []
    for value in list_supply_chain:
        provider = Enterprise.objects.get(pk=value[0])
        recipient = Enterprise.objects.get(pk=value[1])
        list_query.append(
            SupplyChain(
                provider=provider,
                recipient=recipient,
                price=value[2],
                move_date=value[3],
            )
        )
    SupplyChain.objects.bulk_create(list_query)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0006_create_product"),
    ]

    operations = [
        migrations.RunPython(create),
    ]
