# Generated by Django 4.1.3 on 2023-04-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_create_supply_chain_products"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="enterpriseproducts",
            index=models.Index(fields=["products"], name="enterprise_products_idx"),
        ),
        migrations.AddIndex(
            model_name="enterpriseproducts",
            index=models.Index(fields=["enterprise"], name="products_enterprise_idx"),
        ),
        migrations.AddIndex(
            model_name="supplychain",
            index=models.Index(fields=["price"], name="price_idx"),
        ),
        migrations.AddIndex(
            model_name="supplychain",
            index=models.Index(fields=["recipient"], name="supply_chain_recipient_idx"),
        ),
    ]
